// nuxt3/pages/index.vue
<template>
  <div>
    <p>Select a page:</p>
    <ul>
      <li v-for="page in pages">
        <NuxtLink to={{ page.url }}>{{ page.title }}</NuxtLink>
      </li>
    </ul>
  </div>
</template>

<script setup>
import { getContentPages } from '@ssg-demo/cms';

const pages = await getContentPages();
</script>

// nextjs/src/pages/index.tsx
import { ContentPage, getContentPages } from '@ssg-demo/cms';
import Link from 'next/link';

export default function Home({ pages }: any) {
    return (
        <>
            <div>
                <p>Select a page:</p>
                <ul>
                    {pages.map((page: ContentPage) => (
                        <li key={page.url}>
                            <Link key={page.url} href={page.url}>
                                {page.title}
                            </Link>
                        </li>
                    ))}
                </ul>
            </div>
        </>
    );
}

export async function getStaticProps() {
    const pages = await getContentPages();
    return { props: { pages } };
}
